export const maxFileSize = 2 * 1024 * 1024
export const pageMetaDefaults = {
  title: 'Trama',
  description: 'Registrácia ochrannej známky.',
  keywords: 'trama,',
  language: 'sk',
}
export const availableCountries = [
  'Afganistan',
  'Antigua a Barbuda',
  'Albánsko',
  'Arménsko',
  'Rakúsko',
  'Austrália',
  'Azerbajdžan',
  'Bosna a Hercegovina',
  'Bulharsko',
  'Bahrajn',
  'Brunej',
  'Bonaire, Svätý Eustach a Saba',
  'Brazília',
  'Bhután',
  'Botswana',
  'Benelux',
  'Bielorusko',
  'Kanada',
  'Švajčiarsko',
  'Čína',
  'Kolumbia',
  'Kuba',
  'Curaçao',
  'Cyprus',
  'Česká republika',
  'Nemecko',
  'Dánsko',
  'Alžírsko',
  'Estónsko',
  'Egypt',
  'Európska únia',
  'Španielsko',
  'Fínsko',
  'Francúzsko',
  'Spojené kráľovstvo',
  'Gruzínsko',
  'Ghana',
  'Gambia',
  'Grécko',
  'Chorvátsko',
  'Maďarsko',
  'Indonézia',
  'Írsko',
  'Izrael',
  'India',
  'Irán',
  'Island',
  'Taliansko',
  'Japonsko',
  'Keňa',
  'Kirgizsko',
  'Kambodža',
  'Kórejská ľudovodemokratická republika',
  'Kórejská republika',
  'Kazachstan',
  'Laos',
  'Lichtenštajnsko',
  'Libéria',
  'Lesotho',
  'Litva',
  'Lotyšsko',
  'Maroko',
  'Monako',
  'Moldavsko',
  'Čierna Hora',
  'Madagaskar',
  'Severné Macedónsko',
  'Mongolsko',
  'Malawi',
  'Mexiko',
  'Malajzia',
  'Mozambik',
  'Namíbia',
  'Nórsko',
  'Nový Zéland',
  'Africká organizácia duševného vlastníctva (OAPI)',
  'Omán',
  'Filipíny',
  'Poľsko',
  'Portugalsko',
  'Rumunsko',
  'Srbsko',
  'Ruska federácia',
  'Rwanda',
  'Sudán',
  'Švédsko',
  'Singapur',
  'Slovinsko',
  'Slovensko',
  'Sierra Leone',
  'San Maríno',
  'Svätý Tomáš a Princov ostrov',
  'Svätý Martin (holandská časť)',
  'Sýria',
  'Eswatini',
  'Thajsko',
  'Tadžikistan',
  'Turkménsko',
  'Tunisko',
  'Turecko',
  'Ukrajina',
  'USA',
  'Uzbekistan',
  'Vietnam',
  'Samoa',
  'Zambia',
  'Zimbabwe',
]

export const prices = {
  'sk-fee': {
    description: 'Odmena za právne služby spojené so zápisom ochrannej známky (SK)',
    basePrice: 199,
    basePriceExVat: 199, //165.83,
    basePriceVat: 0, //33.17,
  },
  'sk-registration-fee': {
    description: 'Správny poplatok (SK - základný)',
    basePrice: 96,
    basePriceExVat: 96,
    basePriceVat: 0,
  },
  'cz-fee': {
    description: 'Odmena za právne služby spojené so zápisom ochrannej známky (CZ)',
    basePrice: 249,
    basePriceExVat: 249, //207.5,
    basePriceVat: 0, //41.5,
  },
  'cz-registration-fee': {
    description: 'Správny poplatok (CZ - základný)',
    basePrice: 200,
    basePriceExVat: 200,
    basePriceVat: 0,
  },
  'eu-fee': {
    description: 'Odmena za právne služby spojené so zápisom ochrannej známky (EU)',
    basePrice: 449,
    basePriceExVat: 449, //374.16,
    basePriceVat: 0, //74.84,
  },
  'eu-registration-fee': {
    description: 'Správny poplatok (EU - základný)',
    basePrice: 850,
    basePriceExVat: 850,
    basePriceVat: 0,
  },
  'consultation-fee': {
    description: 'Odmena za právne služby - konzultácia tovarov',
    basePrice: 50,
    basePriceExVat: 50, //41.66,
    basePriceVat: 0, //8.34,
  },
  'no-consultation-fee': {
    description: 'Vlastný výber tovarov a služieb',
    basePrice: 0,
    basePriceExVat: 0,
    basePriceVat: 0,
  },
  'sk-categories-fee': {
    description: 'Správny poplatok (SK - triedy navyše)',
    basePrice: 20,
    basePriceExVat: 20,
    basePriceVat: 0,
  },
  'cz-categories-fee': {
    description: 'Správny poplatok (CZ - triedy navyše)',
    basePrice: 20,
    basePriceExVat: 20,
    basePriceVat: 0,
  },
  'eu-second-category-fee': {
    description: 'Správny poplatok (EU - 2. trieda)',
    basePrice: 50,
    basePriceExVat: 50,
    basePriceVat: 0,
  },
  'eu-after-second-category-fee': {
    description: 'Správny poplatok (EU - triedy navyše)',
    basePrice: 150,
    basePriceExVat: 150,
    basePriceVat: 0,
  },
}

export const invoiceBaseId = 200200000
